import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Search, Database, Calendar } from "lucide-react";
import api from "../../services/api";

export function DataCatalog() {
  const [metrics, setMetrics] = useState<any[]>([]);
  const [search, setSearch] = useState("");

  useEffect(() => {
    api.get("/catalog/metrics").then(res => {
      const fetched = res.data.data || [];
      const extraMetrics = [
        { name: "Customer Acquisition Cost (CAC)", status: "Verified", description: "Total sales and marketing cost required to earn a new customer.", formula: "SUM(marketing_spend) / count(new_customers)", allowed_dimensions: ["campaign", "region"], business_owner: "Marketing" },
        { name: "Customer Lifetime Value (LTV)", status: "Verified", description: "Total revenue expected from a single customer account.", formula: "AVG(monthly_revenue) * AVG(lifespan)", allowed_dimensions: ["cohort", "tier"], business_owner: "Finance" },
        { name: "Net Promoter Score (NPS)", status: "Reviewing", description: "Customer satisfaction and loyalty score.", formula: "perc(promoters) - perc(detractors)", allowed_dimensions: ["product", "date"], business_owner: "Product" },
        { name: "Daily Active Users (DAU)", status: "Verified", description: "Unique users active on a given day.", formula: "COUNT(DISTINCT user_id)", allowed_dimensions: ["device", "os"], business_owner: "Engineering" },
        { name: "Monthly Recurring Revenue (MRR)", status: "Verified", description: "Predictable revenue generated by customers every month.", formula: "SUM(subscription_amount)", allowed_dimensions: ["plan", "country"], business_owner: "Finance" },
        { name: "Churn Rate", status: "Verified", description: "Percentage of customers who cancel their subscription.", formula: "canceled_customers / total_customers", allowed_dimensions: ["reason", "tier"], business_owner: "Sales" },
        { name: "Average Revenue Per User (ARPU)", status: "Deprecated", description: "Revenue divided by active users.", formula: "total_revenue / active_users", allowed_dimensions: ["region"], business_owner: "Finance" },
        { name: "Lead Conversion Rate", status: "Verified", description: "Percentage of leads that convert into paying customers.", formula: "converted_leads / total_leads", allowed_dimensions: ["source", "campaign"], business_owner: "Marketing" },
        { name: "Inventory Turnover", status: "Reviewing", description: "How many times inventory is sold and replaced.", formula: "cogs / avg_inventory", allowed_dimensions: ["category", "warehouse"], business_owner: "Operations" },
        { name: "Employee Retention Rate", status: "Verified", description: "Percentage of employees that remain in the company.", formula: "retained_employees / total_employees", allowed_dimensions: ["department", "role"], business_owner: "HR" },
        { name: "Operating Cash Flow", status: "Verified", description: "Cash generated by regular operating activities.", formula: "net_income + non_cash_expenses - change_in_working_capital", allowed_dimensions: ["quarter", "year"], business_owner: "Finance" },
        { name: "Gross Margin", status: "Verified", description: "Percentage of revenue remaining after subtracting COGS.", formula: "(revenue - cogs) / revenue", allowed_dimensions: ["product_line", "region"], business_owner: "Finance" }
      ];
      setMetrics([...fetched, ...extraMetrics]);
    });
  }, []);

  const filtered = metrics.filter(m => m.name.toLowerCase().includes(search.toLowerCase()));

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-extrabold tracking-tight text-foreground">Data Catalog & Glossary</h1>
        <p className="text-muted-foreground">Search governed metric definitions and dimensions.</p>
      </div>

      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={18} />
        <input 
          type="text" 
          placeholder="Search metrics..." 
          value={search}
          onChange={e => setSearch(e.target.value)}
          className="w-full pl-10 pr-4 py-3 bg-secondary/50 border border-border rounded-xl focus:outline-none focus:ring-2 focus:ring-primary"
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {/* Data Quality Score */}
        <div className="glass p-6 rounded-xl border border-border flex items-center justify-between">
          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-1">Overall Data Quality</h3>
            <p className="text-3xl font-bold text-emerald-500">98.4%</p>
            <p className="text-xs text-muted-foreground mt-1">Based on 1.2M records</p>
          </div>
          <div className="w-16 h-16 rounded-full border-4 border-emerald-500/20 border-t-emerald-500 flex items-center justify-center">
            <span className="font-bold text-emerald-500 text-sm">A+</span>
          </div>
        </div>

        {/* Recently Queried */}
        <div className="glass p-6 rounded-xl border border-border">
          <h3 className="text-sm font-medium text-muted-foreground mb-3 flex items-center gap-2">
            <Calendar size={14} /> Recently Queried
          </h3>
          <div className="space-y-3">
            {["Gross Revenue", "Active Users", "Churn Rate"].map((m, i) => (
              <div key={i} className="flex justify-between items-center text-sm">
                <span className="font-medium">{m}</span>
                <span className="text-xs text-muted-foreground">{i * 2 + 1} mins ago</span>
              </div>
            ))}
          </div>
        </div>

        {/* Top Data Owners */}
        <div className="glass p-6 rounded-xl border border-border">
          <h3 className="text-sm font-medium text-muted-foreground mb-3 flex items-center gap-2">
            <Database size={14} /> Top Data Owners
          </h3>
          <div className="space-y-3">
            {[
              { name: "Sarah Chen", score: 142 },
              { name: "Alex Kumar", score: 98 },
              { name: "Data Eng Team", score: 85 }
            ].map((owner, i) => (
              <div key={i} className="flex justify-between items-center text-sm">
                <span className="font-medium flex items-center gap-2">
                  <div className="w-5 h-5 rounded bg-primary/20 text-primary flex items-center justify-center text-[10px] font-bold">
                    {owner.name.charAt(0)}
                  </div>
                  {owner.name}
                </span>
                <span className="text-xs px-2 py-0.5 rounded-full bg-secondary">{owner.score} definitions</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
        <div className="glass p-6 rounded-xl border border-border">
          <h2 className="text-lg font-semibold mb-4 text-primary">Data Source Health & Sync Status</h2>
          <div className="space-y-4">
            {[
              { name: "Production Postgres DW", status: "Healthy", lag: "12s lag", records: "1.4B" },
              { name: "Salesforce CRM Sync", status: "Warning", lag: "45m lag", records: "2.1M" },
              { name: "Stripe Billing Events", status: "Healthy", lag: "Real-time", records: "450K" },
              { name: "Zendesk Support Tickets", status: "Healthy", lag: "5m lag", records: "1.2M" },
              { name: "Snowflake Analytics (Cold)", status: "Syncing", lag: "2h remaining", records: "14B" }
            ].map((src, i) => (
              <div key={i} className="flex justify-between items-center p-3 bg-secondary/20 rounded-lg border border-border/50">
                <div>
                  <h4 className="font-semibold text-sm">{src.name}</h4>
                  <span className="text-xs text-muted-foreground">{src.records} records volume</span>
                </div>
                <div className="flex flex-col items-end">
                  <span className={`text-xs font-bold px-2 py-1 rounded uppercase tracking-wider ${src.status === 'Healthy' ? 'text-emerald-500 bg-emerald-500/10' : src.status === 'Warning' ? 'text-amber-500 bg-amber-500/10' : 'text-blue-500 bg-blue-500/10'}`}>
                    {src.status}
                  </span>
                  <span className="text-xs text-muted-foreground mt-1">{src.lag}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
        
        <div className="glass p-6 rounded-xl border border-border">
          <h2 className="text-lg font-semibold mb-4 text-primary">Key Data Lineage Map</h2>
          <div className="relative border-l-2 border-primary/30 ml-4 space-y-6 py-2">
            <div className="relative pl-6">
              <span className="absolute -left-2 top-1.5 w-3.5 h-3.5 bg-primary rounded-full ring-4 ring-background"></span>
              <p className="text-sm font-semibold">Raw Ingestion (Stripe API)</p>
              <p className="text-xs text-muted-foreground mt-1">`raw_stripe_charges` table</p>
            </div>
            <div className="relative pl-6">
              <span className="absolute -left-2 top-1.5 w-3.5 h-3.5 bg-primary rounded-full ring-4 ring-background"></span>
              <p className="text-sm font-semibold">dbt Transformation (Bronze to Silver)</p>
              <p className="text-xs text-muted-foreground mt-1">Cleanses nulls, maps `user_id` to `customer_id`</p>
            </div>
            <div className="relative pl-6">
              <span className="absolute -left-2 top-1.5 w-3.5 h-3.5 bg-primary rounded-full ring-4 ring-background"></span>
              <p className="text-sm font-semibold">Aggregation (Silver to Gold)</p>
              <p className="text-xs text-muted-foreground mt-1">Creates `fct_monthly_recurring_revenue`</p>
            </div>
            <div className="relative pl-6">
              <span className="absolute -left-2 top-1.5 w-3.5 h-3.5 bg-emerald-500 rounded-full ring-4 ring-background"></span>
              <p className="text-sm font-semibold text-emerald-500">MetricMind Exposed Metric</p>
              <p className="text-xs text-muted-foreground mt-1">`Monthly Recurring Revenue (MRR)`</p>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filtered.map((m, i) => (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }} key={m.name} className="glass p-5 rounded-xl border border-border hover:border-primary/50 transition-colors group cursor-pointer">
            <div className="flex justify-between items-start mb-2">
              <h3 className="text-lg font-bold text-primary group-hover:underline">{m.name}</h3>
              <span className="px-2 py-1 text-[10px] uppercase font-bold tracking-wider rounded-full bg-emerald-500/10 text-emerald-500 border border-emerald-500/20">
                {m.status}
              </span>
            </div>
            <p className="text-sm text-muted-foreground mb-4 line-clamp-2">{m.description}</p>
            
            <div className="space-y-2 text-sm">
              <div className="flex justify-between border-b border-border/50 pb-1">
                <span className="text-muted-foreground">SQL Formula</span>
                <span className="font-mono text-xs truncate max-w-[150px]">{m.formula}</span>
              </div>
              <div className="flex justify-between border-b border-border/50 pb-1">
                <span className="text-muted-foreground">Dimensions</span>
                <span className="truncate max-w-[150px]">{m.allowed_dimensions.join(", ")}</span>
              </div>
              <div className="flex justify-between pb-1">
                <span className="text-muted-foreground">Owner</span>
                <span className="flex items-center gap-1 text-xs"><Database size={12}/> {m.business_owner}</span>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
