import { useState, useEffect } from "react";
import { Code, CheckCircle, Clock } from "lucide-react";
import api from "../../services/api";

export function QueryInspector() {
  const [queries, setQueries] = useState<any[]>([]);

  useEffect(() => {
    // Poll or fetch once. In real app, maybe use websockets for live feed.
    api.get("/governance/queries").then(res => setQueries(res.data.data));
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">AI Query Inspector</h1>
        <p className="text-muted-foreground">Transparent audit log of Semantic SQL generated by the Agent.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-4">
          {queries.length === 0 ? (
            <div className="p-8 text-center text-muted-foreground border border-dashed border-border rounded-xl">
              No queries have been executed yet. Ask the AI something!
            </div>
          ) : queries.map(q => (
            <div key={q.id} className="glass p-5 rounded-xl border border-border">
              <div className="flex justify-between items-start mb-4">
                <div>
                  <div className="text-sm font-medium mb-1">User Asked:</div>
                  <div className="text-lg italic text-muted-foreground">"{q.user_message}"</div>
                </div>
                <div className="flex items-center gap-2">
                  <span className="flex items-center gap-1 text-xs px-2 py-1 bg-secondary rounded-md">
                    <Clock size={12}/> {q.execution_time_ms}ms
                  </span>
                  <span className="flex items-center gap-1 text-xs px-2 py-1 bg-emerald-500/10 text-emerald-500 rounded-md border border-emerald-500/20">
                    <CheckCircle size={12}/> {q.semantic_validation}
                  </span>
                </div>
              </div>
              
              <div className="grid grid-cols-2 gap-4 mb-4 text-sm">
                <div className="bg-secondary/30 p-3 rounded-lg">
                  <span className="text-muted-foreground block text-xs mb-1">Metrics Extracted</span>
                  <div className="font-semibold">{q.metrics.join(", ")}</div>
                </div>
                <div className="bg-secondary/30 p-3 rounded-lg">
                  <span className="text-muted-foreground block text-xs mb-1">Dimensions Extracted</span>
                  <div className="font-semibold">{q.dimensions.length > 0 ? q.dimensions.join(", ") : "None"}</div>
                </div>
              </div>

              <div className="bg-[#1e1e1e] rounded-lg p-4 font-mono text-sm overflow-x-auto">
                <div className="flex items-center gap-2 mb-2 text-xs text-gray-400 border-b border-gray-700 pb-2">
                  <Code size={14}/> GENERATED SQL (Parameterized safely)
                </div>
                <pre className="text-blue-300">{q.generated_sql}</pre>
              </div>
            </div>
          ))}
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          {/* Cost Summary */}
          <div className="glass p-5 rounded-xl border border-border">
            <h3 className="font-semibold mb-4 text-sm flex items-center gap-2">
              Warehouse Compute
            </h3>
            <div className="space-y-4">
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-muted-foreground">Total Bytes Scanned</span>
                  <span className="font-medium">12.4 GB</span>
                </div>
                <div className="h-2 w-full bg-secondary rounded-full overflow-hidden">
                  <div className="h-full bg-primary w-[45%]"></div>
                </div>
              </div>
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-muted-foreground">Estimated Cost</span>
                  <span className="font-medium">$0.06</span>
                </div>
                <div className="h-2 w-full bg-secondary rounded-full overflow-hidden">
                  <div className="h-full bg-emerald-500 w-[15%]"></div>
                </div>
              </div>
              <div className="pt-2 mt-2 border-t border-border/50">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Semantic Cache Hit Rate</span>
                  <span className="font-bold text-emerald-500">84.2%</span>
                </div>
              </div>
            </div>
          </div>

          {/* AI Optimization Recommendations */}
          <div className="glass p-5 rounded-xl border border-primary/20 bg-primary/5">
            <h3 className="font-semibold mb-3 text-sm text-primary flex items-center gap-2">
              AI Optimizations
            </h3>
            <div className="space-y-3">
              <div className="p-3 bg-background/50 rounded-lg border border-border text-sm">
                <p className="font-medium mb-1">Index Recommendation</p>
                <p className="text-xs text-muted-foreground">Adding a composite index on <code className="bg-secondary px-1 rounded">orders(region_id, date)</code> could improve query time by ~42%.</p>
              </div>
              <div className="p-3 bg-background/50 rounded-lg border border-border text-sm">
                <p className="font-medium mb-1">Materialized View</p>
                <p className="text-xs text-muted-foreground">The AI frequently queries 'Revenue by Region'. Consider materializing this in the warehouse.</p>
              </div>
            </div>
            <button className="w-full mt-4 py-2 text-xs font-medium bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors">
              Apply Optimizations
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
