import { useState, useEffect } from "react";
import { Code, CheckCircle, Clock } from "lucide-react";
import api from "../../services/api";

export function QueryInspector() {
  const [queries, setQueries] = useState<any[]>([]);

  useEffect(() => {
    // Poll or fetch once. In real app, maybe use websockets for live feed.
    api.get("/governance/queries").then(res => setQueries(res.data.data));
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">AI Query Inspector</h1>
        <p className="text-muted-foreground">Transparent audit log of Semantic SQL generated by the Agent.</p>
      </div>

      <div className="space-y-4">
        {queries.length === 0 ? (
          <div className="p-8 text-center text-muted-foreground border border-dashed border-border rounded-xl">
            No queries have been executed yet. Ask the AI something!
          </div>
        ) : queries.map(q => (
          <div key={q.id} className="glass p-5 rounded-xl border border-border">
            <div className="flex justify-between items-start mb-4">
              <div>
                <div className="text-sm font-medium mb-1">User Asked:</div>
                <div className="text-lg italic text-muted-foreground">"{q.user_message}"</div>
              </div>
              <div className="flex items-center gap-2">
                <span className="flex items-center gap-1 text-xs px-2 py-1 bg-secondary rounded-md">
                  <Clock size={12}/> {q.execution_time_ms}ms
                </span>
                <span className="flex items-center gap-1 text-xs px-2 py-1 bg-emerald-500/10 text-emerald-500 rounded-md border border-emerald-500/20">
                  <CheckCircle size={12}/> {q.semantic_validation}
                </span>
              </div>
            </div>
            
            <div className="grid grid-cols-2 gap-4 mb-4 text-sm">
              <div className="bg-secondary/30 p-3 rounded-lg">
                <span className="text-muted-foreground block text-xs mb-1">Metrics Extracted</span>
                <div className="font-semibold">{q.metrics.join(", ")}</div>
              </div>
              <div className="bg-secondary/30 p-3 rounded-lg">
                <span className="text-muted-foreground block text-xs mb-1">Dimensions Extracted</span>
                <div className="font-semibold">{q.dimensions.length > 0 ? q.dimensions.join(", ") : "None"}</div>
              </div>
            </div>

            <div className="bg-[#1e1e1e] rounded-lg p-4 font-mono text-sm overflow-x-auto">
              <div className="flex items-center gap-2 mb-2 text-xs text-gray-400 border-b border-gray-700 pb-2">
                <Code size={14}/> GENERATED SQL (Parameterized safely)
              </div>
              <pre className="text-blue-300">{q.generated_sql}</pre>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
